<a href="https://colab.research.google.com/github/joydebmahata/Experimental_Data_Interpret/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
import numpy as np
# from matplotlib import pyplot as plt
df = pd.read_csv("/model task 1.csv")
data = df
print("\n")
print(data.keys())
print('\n')
print(data.shape)
print(data)

Index(['Shell OD (mm)', 'Shell ID (mm)', 'Tube dia ref no (inch)',
       'Tube OD (mm)', 'Tube ID (mm)', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10'],
      dtype='object')


(245, 11)
     Shell OD (mm)  Shell ID (mm)  Tube dia ref no (inch)  Tube OD (mm)  \
0            73.03          68.81                  0.2500         6.350
1           141.30         128.20                  0.1250         3.175
2           141.30         128.20                  0.1250         3.175
3           141.30         128.20                  0.1250         3.175
4           141.30         128.20                  0.1875         4.750
..             ...            ...                     ...           ...
240            NaN            NaN                     NaN           NaN
241            NaN            NaN                     NaN           NaN
242            NaN            NaN                     NaN           NaN
243            NaN            NaN                     NaN           NaN
244            NaN            NaN                     NaN           NaN

     Tube ID (mm)  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0           5.350         NaN         NaN         NaN         NaN         NaN
1           1.651         NaN         NaN         NaN         NaN         NaN
2           1.651         NaN         NaN         NaN         NaN         NaN
3           1.651         NaN         NaN         NaN         NaN         NaN
4           3.250         NaN         NaN         NaN         NaN         NaN
..            ...         ...         ...         ...         ...         ...
240           NaN         NaN         NaN         NaN         NaN         NaN
241           NaN         NaN         NaN         NaN         NaN         NaN
242           NaN         NaN         NaN         NaN         NaN         NaN
243           NaN         NaN         NaN         NaN         NaN         NaN
244           NaN         NaN         NaN         NaN         NaN         NaN

                                           Unnamed: 10
0                                                  NaN
1                                                  NaN
2                                                  NaN
3    Calculate mean median mode max min skewness st...
4                                                  NaN
..                                                 ...
240                                                NaN
241                                                NaN
242                                                NaN
243                                                NaN
244                                                NaN

[245 rows x 11 columns]

In [ ]:
# print("column name :\n")
# print(data.columns.tolist())
total_row = len(data)
print(total_row)

# print(data.dtypes)
numeric_cols = data.select_dtypes(include='number').columns.tolist()
i=0
while i < 5:
  col_data = data[numeric_cols[i]].dropna()
  mean_val = col_data.mean()
  median_val = col_data.median()
  mode_val = col_data.mode()
  mode_val = mode_val.iloc[0] if not mode_val.empty else None
  max_val = col_data.max()
  min_val = col_data.min()
  skewness = col_data.skew()
  std_dev = col_data.std()

  print(f"Stats for column '{i}':")
  print(f"  Mean   : {mean_val}")
  print(f"  Median : {median_val}")
  print(f"  Mode   : {mode_val}")
  print(f"  Max    : {max_val}")
  print(f"  Min    : {min_val}")
  print(f"  skew    : {skewness}")
  print(f"  std_dev   : {std_dev}")
  print('\n')
  i=i+1

245
Stats for column '0':
  Mean   : 128.98010101010095
  Median : 141.3
  Mode   : 141.3
  Max    : 141.3
  Min    : 73.03
  skew    : -1.1330187107686311
  std_dev   : 17.115496528534145


Stats for column '1':
  Mean   : 116.47949494949496
  Median : 128.2
  Mode   : 128.2
  Max    : 128.2
  Min    : 68.81
  skew    : -1.0530002927953743
  std_dev   : 16.127192802887443


Stats for column '2':
  Mean   : 0.17613636363636365
  Median : 0.1875
  Mode   : 0.125
  Max    : 0.25
  Min    : 0.125
  skew    : 0.3520351994501
  std_dev   : 0.05157255727800351


Stats for column '3':
  Mean   : 4.47020202020202
  Median : 4.75
  Mode   : 3.175
  Max    : 6.35
  Min    : 3.175
  skew    : 0.36084456278996735
  std_dev   : 1.3091401445051873


Stats for column '4':
  Mean   : 2.9647878787878796
  Median : 3.25
  Mode   : 1.651
  Max    : 5.35
  Min    : 1.651
  skew    : 0.3714026738856506
  std_dev   : 1.3293376997029678

In [ ]:
print(numeric_cols)

['Shell OD (mm)', 'Shell ID (mm)', 'Tube dia ref no (inch)', 'Tube OD (mm)', 'Tube ID (mm)', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']

In [ ]:
print(df.head(70))
print("hgvhv\n")
df.tail(65)

    Shell OD (mm)  Shell ID (mm)  Tube dia ref no (inch)  Tube OD (mm)  \
0           73.03          68.81                  0.2500         6.350
1          141.30         128.20                  0.1250         3.175
2          141.30         128.20                  0.1250         3.175
3          141.30         128.20                  0.1250         3.175
4          141.30         128.20                  0.1875         4.750
..            ...            ...                     ...           ...
65         141.30         128.20                  0.2500         6.350
66         141.30         128.20                  0.1250         3.175
67         141.30         128.20                  0.2500         6.350
68         141.30         128.20                  0.1875         4.750
69         141.30         128.20                  0.2500         6.350

    Tube ID (mm)  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0          5.350         NaN         NaN         NaN         NaN         NaN
1          1.651         NaN         NaN         NaN         NaN         NaN
2          1.651         NaN         NaN         NaN         NaN         NaN
3          1.651         NaN         NaN         NaN         NaN         NaN
4          3.250         NaN         NaN         NaN         NaN         NaN
..           ...         ...         ...         ...         ...         ...
65         4.830         NaN         NaN         NaN         NaN         NaN
66         1.651         NaN         NaN         NaN         NaN         NaN
67         4.830         NaN         NaN         NaN         NaN         NaN
68         3.250         NaN         NaN         NaN         NaN         NaN
69         4.830         NaN         NaN         NaN         NaN         NaN

                                          Unnamed: 10
0                                                 NaN
1                                                 NaN
2                                                 NaN
3   Calculate mean median mode max min skewness st...
4                                                 NaN
..                                                ...
65                                                NaN
66                                                NaN
67                                                NaN
68                                                NaN
69                                                NaN

[70 rows x 11 columns]
hgvhv

,Shell OD (mm),Shell ID (mm),Tube dia ref no (inch),Tube OD (mm),Tube ID (mm),Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Shell OD (mm)           99 non-null     float64
 1   Shell ID (mm)           99 non-null     float64
 2   Tube dia ref no (inch)  99 non-null     float64
 3   Tube OD (mm)            99 non-null     float64
 4   Tube ID (mm)            99 non-null     float64
 5   Unnamed: 5              0 non-null      float64
 6   Unnamed: 6              0 non-null      float64
 7   Unnamed: 7              0 non-null      float64
 8   Unnamed: 8              0 non-null      float64
 9   Unnamed: 9              0 non-null      float64
 10  Unnamed: 10             1 non-null      object
dtypes: float64(10), object(1)
memory usage: 21.2+ KB